version: "2"
services:
    jekyll:
        image: jekyll/jekyll:3.8
        command: jekyll serve --force_polling
        ports:
            - 3000:3000
        volumes:
            - .:/srv/jekyll
            - ./_site:/srv/jekyll/_site
        environment:
            JEKYLL_UID: 1000
            JEKYLL_GID: 1000
